baseURL = "https://seusite.com/"
languageCode = "pt-br"
title = "Evandro Santos"
theme = "GoHuBlogfolio"
enableRobotsTXT = true

[pagination]
  pagerSize = 6

[taxonomies]
  category = "categories"
  tag = "tags"